---
title: "Main exploratory analysis"
author: "Luis"
date: "03/2022"
output: html_document
---
## Full Model:
# CDI vocabulary ~  ids_pref:test_age + ids_pref:cdi_age + ids_pref:protocol + ids_pref + cdi_age + gender + (1 + ids_pref:test_age + ids_pref:cdi_age + ids_pref:protocol + ids_pref + cdi_age + gender | lab)
## Pruned Model:
# CDI_vocabulary ~  ids_pref:test_age + ids_pref:cdi_age + ids_pref:protocol + ids_pref + cdi_age + gender + protocol + test_age + ids_pref : nae + nae + (1 | lab) + (1| participant)
```{r setup, echo = FALSE, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
```

```{r libraries, echo = FALSE, include = FALSE}
library(dplyr)
library(glmmTMB)
library(ggplot2)
library(lmtest)
library(rstatix)
```

```{r preprocessing}
rm(list = ls())

source("C:/Projects/Roger's course/r-files/glmmTMB_stability.r")
source("C:/Projects/Roger's course/r-files/diagnostic_fcns.r")
# Load data from a .txt file
imported <- read.delim("data/cdi_percentile/percentiles_manybabies_cdi.txt", stringsAsFactors = TRUE, header = TRUE) 

data <- data.frame(vocabulary_percentile = imported$daily_percentile, ids_pref = imported$IDS_pref, test_age = imported$age_days, cdi_age = imported$CDI.agedays, protocol = imported$method, gender = imported$gender, lab = imported$labid, participant = imported$subid_unique, nae = imported$nae, vocab_nwords = imported$vocab_nwords, cdi.age_range = imported$CDI.agerange)

data$cdi.age_range <- as.factor(data$cdi.age_range)
#investigate the distribution of each variable
hist(data$vocabulary_percentile) #evenly distributed

hist(data$ids_pref) #normally distributed

hist(data$test_age) #normally distributed

hist(data$cdi_age) #bimodal distribution

#vocabulary ~ cdi_age_Cat + gender + lab

plot(data$protocol) # head-turn preference design is most prevalent.

plot(data$gender) # roughly equal numbers of each gender

plot(data$lab) # fairly large variance in numbers from each lab

plot(data$participant) # some infants seem to have been tested multiple times

plot(table(data$nae)) # few more non-nae

#ensuring the response variable is between 0 and 1, as is required for a beta error model.
data$vocabulary_percentile[data$vocabulary_percentile == 0] <- 1
if(data$vocabulary_percentile > 1)
{
  data$vocabulary_percentile <- data$vocabulary_percentile/100
}
full.fe.re <- fe.re.tab(fe.model = "vocabulary_percentile ~ ids_pref * test_age + ids_pref * cdi.age_range + ids_pref * protocol + ids_pref * nae + gender", re = c("lab", "participant"), data = data)
full.fe.re_test <- fe.re.tab(fe.model = "vocab_nwords ~ ids_pref * test_age + ids_pref * cdi.age_range + ids_pref * protocol + ids_pref * nae + gender", re = c("lab", "participant"), data = data)

full.fe.re_test$summary
library("lme4")
t.data <- full.fe.re$data

#z transformation of the predictors to help with the interpretation of the model.
t.data$z.ids_pref <- as.vector(scale(t.data$ids_pref))
t.data$z.test_age <- as.vector(scale(t.data$test_age))

#Running the mixed effects model with a beta error distribution for the response variable.
full <- glmmTMB(vocabulary_percentile ~ z.ids_pref * z.test_age + z.ids_pref * cdi.age_range + z.ids_pref * protocol + z.ids_pref * nae + gender + (1 + ids_pref * cdi.age_range + ids_pref * test_age || lab) + (1 + cdi.age_range || participant), family = beta_family(link = "logit"), data = t.data)

summary(full)$varcor

overdisp.test(full)

ranef.diagn.plot(full)

coll_model <- lm(vocabulary_percentile ~ z.ids_pref + z.test_age + cdi.age_range + protocol + nae + gender, data = t.data)

summary(full)

library(car)
vif(coll_model)

full.stab <- glmmTMB.stab(model.res = full, para = TRUE, data = t.data)

table(full.stab$detailed$converged)
m.stab.plot(full.stab$summary[, -1])

null <- glmmTMB(vocabulary_percentile ~ z.test_age + cdi.age_range + protocol + nae + gender + (1 + ids_pref * cdi.age_range + ids_pref * test_age || lab) + (1 + cdi.age_range || participant), family = beta_family(link = "logit"), data = t.data)
round(summary(full)$coefficients$cond, 3)

as.data.frame(anova(null, full, test="Chisq"))

full.test <- lmer(vocab_nwords ~  z.ids_pref * z.test_age + z.ids_pref * cdi.age_range + z.ids_pref * protocol + z.ids_pref * nae + gender + (1 + gender + cdi.age_range + ids_pref + test_age | lab) + (1 | participant), data = t.data)

summary(full.test)$varcor

diagnostics.plot(full.test)

source("C:/Projects/Roger's course/r-files/glmm_stability.r")
full.stab_test=glmm.model.stab(model.res=full.test, contr=NULL, para=F,
data=NULL)

full.stab_test
table(full.stab_test$detailed$lme4.warnings)
table(full.stab_test$detailed$opt.warnings)
round(full.stab$summary[, -1], 3)

m.stab.plot(full.stab_test$summary[, -1])

summary(full.test)
```

```{r plots, include = TRUE, warning= FALSE}

only_nae <- t.data[t.data$nae == TRUE,]
ggplot(data = only_nae, aes(x = nae , y = vocabulary_percentile, colour = cdi.age_range)) +
  geom_point() +
  geom_boxplot() +
  # ylim(0,1)
   facet_wrap(.~ lab)

ggplot(data = t.data, aes(x = gender , y = vocab_nwords, color = cdi.age_range)) +
  geom_point()+
  geom_boxplot() +
  facet_wrap(.~ lab)
```

